- name: Debian backports repo for pacemaker
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://ftp.de.debian.org/debian jessie-backports main'

- name: Install ha dependencies from backports
  apt: name={{ item }} state=present default_release=jessie-backports update_cache=yes install_recommends=no
  with_items:
    - corosync
    - pacemaker
    - crmsh
