- name: Debian backports repo for pacemaker
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://ftp.de.debian.org/debian jessie-backports main'

- name: Install ha dependencies from backports
  apt: name={{ packages }} state=present default_release=jessie-backports update_cache=yes install_recommends=no
  vars:
    packages:
      - corosync
      - pacemaker
      - crmsh
